import { ProjectInterface } from "../types/project";

export const projectData: ProjectInterface[] = [
  {
    title: "MicroFlow <br/>",
    year: 2024,
    tag: 0,
    image: "image/microflow.png",
    url: "https://bike-micro-flow-seoul.netlify.app/",
    imagedark: true,
  },
  {
    title: "Population Garden <br/>",
    year: 2023,
    tag: 0,
    image: "image/pop.gif",
    url: "https://seoul-pop-garden.netlify.app/",
    imagedark: true,
  },
  {
    title: "TinyBike <br/>",
    year: 2024,
    tag: 3,
    image: "image/tinybike.gif",
    imagedark: true,
  },
  {
    title: "Restaurant Survival Prediction",
    year: 2024,
    tag: 0,
    image: "image/restaurant.png",
    url: "https://teamgigo.netlify.app/",
    imagedark: true,
  },
  {
    title: "Accessibility Dashboard",
    year: 2021,
    tag: 0,
    image: "image/transportation_accessiblity.png",
    url: "https://aete.github.io/transport-accessibility/",
  },
  {
    title: "D3 Practice <br/>",
    year: 2021,
    tag: 1,
    image: "image/d3Practice.png",
    url: "https://hancodesd3.netlify.app/",
  },
  {
    title: "Work zone traffic<br/>dashboard",
    year: 2020,
    tag: 0,
    image: "image/workzone2.png",
    url: "https://workzone-collision-analysis.github.io/capstone/dashboard/",
  },
  {
    title: "Work zone traffic analysis",
    year: 2020,
    tag: 2,
    image: "image/workzone.png",
    url: "https://workzone-collision-analysis.github.io/",
  },
  {
    title: "Mini projects InfoViz, Spring `20",
    year: 2020,
    tag: 1,
    image: "image/infoviz.png",
    url: "https://hancodesinfoviz.netlify.app/",
  },
  {
    title: "Seoul Living-Pop<br>Dashboard",
    year: 2020,
    tag: 0,
    image: "image/livingpop_dash.png",
    url: "https://seoul-pop-garden.netlify.app/",
  },
  {
    title: "Make it Green<br>Dashboard",
    year: 2019,
    tag: 0,
    image: "image/jc_dashboard.png",
    url: "https://aete.github.io/jc_datadashboard_prototype/",
  },
  {
    title: "Plan Generator",
    year: 2018,
    tag: 3,
    image: "image/plan.gif",
  },
  {
    title: "Dwelling by Walling",
    year: 2016,
    tag: 2,
    image: "image/dwelling.png",
  },
  {
    title: "The Frame",
    year: 2016,
    tag: 2,
    image: "image/theframe.jpg",
    imagedark: true,
  },
  {
    title: "QR City",
    year: 2013,
    tag: 3,
    image: "image/qrcity.gif",
  },
  {
    title: "Github",
    year: -1,
    tag: 4,
    image: "image/github.jpg",
    url: "https://github.com/aete",
  },
  {
    title: "Linkedin",
    year: -1,
    tag: 4,
    image: "image/linkedin.png",
    url: "https://www.linkedin.com/in/seunggyunhancodes/",
  },
];
