import { ProjectInterface } from "../types/project";

export const projectData: ProjectInterface[] = [
  {
    title: "No Kill Colorado",
    year: 2025,
    tag: 1,
    image: "image/nkc.png",
    url: "https://dcm-nkc-seunggyun.netlify.app/",
    summary: "Data analysis and visualization for animal shelter outcomes.",
    tool: "D3.js",
  },
  {
    title: "Watermelon Dice",
    year: 2025,
    tag: 3,
    image: "image/watermelon_dice.png",
    imagedark: false,
    summary: "Generative art drawings.",
    tool: "p5.js",
  },
  {
    title: "Data Terrain",
    year: 2025,
    tag: 0,
    image: "image/dataterrain.png",
    url: "https://github.com/Aete/dataTerrain",
    imagedark: true,
    summary: "Visualization Interface between public and the open data portal.",
    tool: "three.js, deck.gl",
  },
  {
    title: "MicroFlow <br/>",
    year: 2024,
    tag: 0,
    image: "image/microflow.gif",
    url: "https://bike-micro-flow-seoul.netlify.app/",
    imagedark: true,
    summary: "Visualization of public bike usage in Magok district, Seoul.",
    tool: "deck.gl",
  },
  {
    title: "Population Garden <br/>",
    year: 2023,
    tag: 0,
    image: "image/pop.gif",
    url: "https://seoul-pop-garden.netlify.app/",
    imagedark: true,
    summary: "Data-driven art with Seoul living population dataset.",
    tool: "p5.js, d3.js",
  },
  {
    title: "Accessibility Dashboard",
    year: 2021,
    tag: 0,
    image: "image/transportation_accessiblity.png",
    url: "https://aete.github.io/transport-accessibility/",
    summary:
      "Visualization of transportation accessibility in Gangnam district.",
    tool: "mapboxgl, d3.js",
  },
  {
    title: "D3 Practice <br/>",
    year: 2021,
    tag: 1,
    image: "image/d3Practice.png",
    url: "https://hancodesd3.netlify.app/",
    summary: "Personal practice of D3.js with various graphs.",
    tool: "d3.js",
  },
  {
    title: "Work zone traffic<br/>dashboard",
    year: 2020,
    tag: 0,
    image: "image/workzone2.png",
    url: "https://workzone-collision-analysis.github.io/capstone/dashboard/",
    summary:
      "Dashboard for traffic accidents and 511 events. Capstone in spring 2020, NYU.",
    tool: "mapboxgl, chart.js",
  },
  {
    title: "Work zone traffic analysis",
    year: 2020,
    tag: 2,
    image: "image/workzone.png",
    url: "https://workzone-collision-analysis.github.io/",
    summary:
      "Analysis of traffic accidents and 511 events. Capstone in spring 2020, NYU.",
    tool: "geopandas, sklearn",
  },
  {
    title: "Mini projects InfoViz, Spring `20",
    year: 2020,
    tag: 1,
    image: "image/infoviz.png",
    url: "https://hancodesinfoviz.netlify.app/",
    summary: "Mini projects of Info viz class in Spring 2020, NYU.",
    tool: "d3.js",
  },
  {
    title: "Seoul Living-Pop<br>Dashboard",
    year: 2020,
    tag: 0,
    image: "image/livingpop_dash.png",
    url: "https://seoul-pop-garden.netlify.app/",
    summary: "Dashboard for Seoul living population data.",
    tool: "d3.js",
  },
  {
    title: "Make it Green<br>Dashboard",
    year: 2019,
    tag: 0,
    image: "image/jc_dashboard.png",
    url: "https://aete.github.io/jc_datadashboard_prototype/",
    summary:
      "Dashboard for Jersey City's CSO problem. Civic Analytics class in fall 2019, NYU.",
    tool: "mapboxgl, d3.js",
  },
  {
    title: "Plan Generator",
    year: 2018,
    tag: 3,
    image: "image/plan.gif",
    summary: "Experiment of generating small house plans with deep learning.",
    tool: "tensorflow",
  },
  {
    title: "Dwelling by Walling",
    year: 2016,
    tag: 2,
    image: "image/dwelling.png",
    summary: "Co-living residential building design with flexible wall system.",
  },
  {
    title: "The Frame",
    year: 2016,
    tag: 2,
    image: "image/theframe.jpg",
    imagedark: true,
    summary:
      "Waterfront culture complex building design. Graduation project in spring 2016, SKKU",
  },
  {
    title: "QR City",
    year: 2013,
    tag: 3,
    image: "image/qrcity.gif",
    summary: "Interactive urban planning tool with QR code.",
    tool: "processing",
  },
  {
    title: "Github",
    year: -1,
    tag: 4,
    image: "image/github.jpg",
    url: "https://github.com/aete",
  },
  {
    title: "Linkedin",
    year: -1,
    tag: 4,
    image: "image/linkedin.png",
    url: "https://www.linkedin.com/in/seunggyunhancodes/",
  },
];
