import { Project } from "../interface/project";

export const projectData: Project[] = [
  {
    title: "Population Garden",
    year: 2023,
    tag: 0,
    image: "image/pop.gif",
    url: "https://seoul-pop-garden.netlify.app/",
  },
  {
    title: "Accessibility Dashboard",
    year: 2021,
    tag: 0,
    image: "image/transportation_accessiblity.png",
    url: "https://www.han.codes/transport-accessibility/",
  },
  {
    title: "Work zone traffic<br/>dashboard",
    year: 2020,
    tag: 0,
    image: "image/workzone2.png",
    url: "https://workzone-collision-analysis.github.io/capstone/dashboard/",
  },
  {
    title: "Work zone traffic analysis",
    year: 2020,
    tag: 2,
    image: "image/workzone.png",
    url: "https://workzone-collision-analysis.github.io/",
  },
  {
    title: "Mini projects InfoViz, Spring `20",
    year: 2020,
    tag: 1,
    image: "image/infoviz.png",
    url: "https://hancodesinfoviz.netlify.app/",
  },
  {
    title: "Seoul Living-Pop<br>Dashboard",
    year: 2020,
    tag: 0,
    image: "image/livingpop_dash.png",
    url: "https://seoul-pop-garden.netlify.app/",
  },
  {
    title: "Make it Green<br>Dashboard",
    year: 2019,
    tag: 0,
    image: "image/jc_dashboard.png",
    url: "https://seoul-pop-garden.netlify.app/",
  },
  {
    title: "Plan Generator",
    year: 2018,
    tag: 4,
    image: "image/plan.gif",
    url: "https://seoul-pop-garden.netlify.app/",
  },
  {
    title: "Dwelling by Walling",
    year: 2016,
    tag: 3,
    image: "image/dwelling.png",
    url: "https://seoul-pop-garden.netlify.app/",
  },
  {
    title: "The Frame",
    year: 2016,
    tag: 3,
    image: "image/theframe.jpg",
    url: "https://seoul-pop-garden.netlify.app/",
  },
  {
    title: "QR City",
    year: 2013,
    tag: 4,
    image: "image/qrcity.gif",
    url: "https://seoul-pop-garden.netlify.app/",
  },
  {
    title: "Github",
    year: -1,
    tag: 5,
    image: "image/github.jpg",
    url: "https://github.com/aete",
  },
  {
    title: "Linkedin",
    year: -1,
    tag: 5,
    image: "image/linkedin.png",
    url: "https://www.linkedin.com/in/seunggyunhancodes/",
  },
];
